name: Build SnapSort

on:
  release:
    types: [published] # Triggers when a release is published

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            pyinstaller main.py -F --windowed --noconfirm --collect-all face_recognition_models --name SnapSort.exe
          else
            pyinstaller main.py -F --noconfirm --collect-all face_recognition_models --name SnapSort
          fi
        shell: bash

      - name: Rename and package executable for Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir release-package
          Copy-Item "dist\\SnapSort.exe" -Destination "release-package\\SnapSort.exe"
          Set-Location release-package
          Compress-Archive -Path * -DestinationPath ..\\SnapSort-Windows.zip
        shell: pwsh

      - name: Rename and package executable for macOS
        if: matrix.os == 'macos-latest'
        run: |
          mkdir release-package
          cp dist/SnapSort release-package/SnapSort
          chmod +x release-package/SnapSort
          cd release-package
          zip -r ../SnapSort-macOS.zip *
        shell: bash

      - name: Rename and package executable for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir release-package
          cp dist/SnapSort release-package/SnapSort
          chmod +x release-package/SnapSort
          cd release-package
          zip -r ../SnapSort-Linux.zip *
        shell: bash

      - name: Upload build to release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: |
            SnapSort-*.zip
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
