name: Build SnapSort for Windows

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller main.py -F --collect-all face_recognition_models --name SnapSort.exe

      - name: Package executable
        run: |
          mkdir release-package
          copy dist\SnapSort.exe release-package\SnapSort.exe
          cd release-package
          7z a -tzip ..\SnapSort-Windows.zip *
        shell: cmd

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SnapSort-Windows
          path: SnapSort-Windows.zip
